name: Example2

on:
  workflow_dispatch:

jobs:
  getrepowh:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get-repo-wh
        with:
          route: GET https://api.github.com/repos/velivalab/ghanode-js/hooks/408427779
          owner: velivalab
          repo: ghademo-nodejs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: "echo latest release: '${{ steps.get-repo-wh.outputs.data }}'"
