name: Example3

on:
  workflow_dispatch:

jobs:
  getrepowh:
    runs-on: ubuntu-latest
    steps:
      - name: install npm packages
        run: npm i axios
        
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const axios = require("axios");
            const result = (await axios.get(`api.github.com/repos/velivalab/ghademo-nodejs/hooks/408427779`, {
              headers: { Authorization: `Bearer ${{ secrets.GITHUB_TOKEN }}` }})).data;
            console.log(`echo output: `+result)
