name: Example3

on:
  workflow_dispatch:

jobs:
  getrepowh:
    runs-on: ubuntu-latest
    steps:
      - name: display repo variables
        run: npm i axios
        
      - name: install npm packages
        run: echo repo variable ${{ vars.SN_DEVOPS_TOKEN }}
        
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const axios = require("axios");
            const ghToken = Buffer.from("${{secrets.GH_TOKEN}}");
            console.log(`echo ghToken: `+ghToken);
            const result = (await axios.get(`api.github.com/repos/velivalab/ghademo-nodejs/hooks/408427779`, {
              headers: { Authorization: `Bearer ${ghToken}` }})).data;
            console.log(`echo output: `+result);
