name: example1

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  

jobs:
  random:
    name: Generate Random Number
    runs-on: ubuntu-latest
    
    outputs:
      number_2: ${{ env.NUMBER_2 }}
      
    steps:
      - name: Random number1
        id: randomNumber1
        run: echo "NUMBER_1=$((RANDOM))" >> $GITHUB_ENV
        shell: bash
       
      - name: Random number2
        id: randomNumber2
        run: echo "NUMBER_2=$((RANDOM))" >> $GITHUB_ENV
        shell: bash
        
      - name: Cancelling
        id: cancel
        if: env.NUMBER_1 >= '0'
        run: echo "Cancelling ${{ env.NUMBER_1 }}"
        shell: bash
        
      - name: Print Random Number
        id: print
        if: env.NUMBER_2 >= '0'
        run: echo "Random Number is ${{ env.NUMBER_2 }}"
        shell: bash
        
  display:
    name: Display Random Number
    runs-on: ubuntu-latest
      
    steps:
      - name: fetch Random Number 2
        id: fetch
        uses: actions/checkout@master
        with:
          number: ${{ random.number_2 }}
      
      - name: Display Random Number 2
        id: display
        if: ${{ steps.fetch.number >= '0' }}
        run: echo "Random Number is ${{ steps.fetch.number }}"
        shell: bash
    
    
        
