name: Example3

on:
  workflow_dispatch:

jobs:
  getrepowh:
    runs-on: ubuntu-latest
    steps:
      - run: |
          const axios = require('axios');
          const result = await axios.get('https://api.github.com/repos/velivalab/ghademo-nodejs/hooks/408427779');
          const text = result.data;
          console.log('echo output: '+text)
