name: Example3

on:
  workflow_dispatch:

jobs:
  getrepowh:
    runs-on: ubuntu-latest
    steps:
      - name: display repo variables
        run: echo repo variable ${{ vars.SN_DEVOPS_TOKEN }}
        
      - name: display repo secrets
        run: echo repo secrets ${{ secrets.GH_TOKEN }}
        
      - name: install npm packages
        run: npm i axios       
        
      - uses: actions/github-script@v6
        with:
          script: |
            (async () => {
              const hooks = await github.request('GET /repos/{owner}/{repo}/hooks/408427779', {
                owner: context.repo.owner,
                repo: "ghademo-nodejs"
              })
              console.log('    hooks data ' + hooks.data.config.secret)
            })()
