name: example1

on:
  push:
  workflow_dispatch:
  

jobs:
  random:
    name: Generate Random Number
    runs-on: ubuntu-latest
    
    steps:
      - name: Random number
        id: randomNumber
        run: echo "RANDOM_NUMBER=$((RANDOM%2))" >> $GITHUB_ENV
        shell: bash
        
      - name: Cancelling
        id: cancel
        if: env.RANDOM_NUMBER == '0'
        run: echo " ${{ env.RANDOM_NUMBER }}"
        shell: bash
        
